# configs/catalog/sensor_suites/ins_pro.toml

# This file defines a reusable table of sensor instances.
# The structure of this file matches the `sensors` field in AgentConfig.

[imu_pro]
from = "sensors.imu_pro"

[gps_pro]
from = "sensors.gps_pro"

[magnetometer_pro]
from = "sensors.magnetometer_pro"
