# Cargo.toml
[package]
name = "rust_robotics"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.0"
nalgebra = "0.33.2"
num-traits = "0.2.19"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.21"
