# helios_sim/assets/catalog/sensors/gps_pro.toml
# Corresponds to the `SensorConfig::Gps` enum variant.
kind = "Gps"
name = "gps_advanced"
rate = 10.0
# --- Noise Characteristics ---
# Standard deviation in meters [East, North, Up].
# This simulates real-world GPS performance in open sky.
# Horizontal accuracy is usually better than vertical accuracy.
# 2cm horizontal, 5cm vertical sigma
noise_stddev = [0.02, 0.02, 0.05]
# Place the antenna on the roof, slightly forward.
# This is a good, realistic spot for clear sky view.
# [x, y, z] in the body frame: Forward, Left, Up.
transform = { translation = [0.0, 0.0, 0.0], rotation = [0, 0, 0] }
