# helios_sim/assets/catalog/sensors/imu_pro.toml
# Corresponds to the `SensorConfig::Imu` enum variant.
kind = "Imu"
# Corresponds to the `ImuConfig::SixDof` variant.
type = "SixDof"
name = "imu_pro"
rate = 100.0
transform = { translation = [0.0, 0.0, 0.0], rotation = [0.0, 0.0, 0.0] }
accel_noise_stddev = [0.01, 0.01, 0.01]
gyro_noise_stddev = [0.001, 0.001, 0.001]
