# helios_sim/assets/catalog/sensors/lidar2d.toml
kind = "Lidar"                                # <-- Matches SensorConfig::Lidar
type = "Lidar2D"                              # <-- This is the `tag` for the inner LidarConfig enum
rate = 10.0
transform = { translation = [1.5, 0.0, 0.5] } # Mounted on the front bumper
max_range = 50.0
horizontal_fov = 180.0                        # A forward-facing scanner
horizontal_beams = 360
range_noise_stddev = 0.03

debug_visuals = true
