[package]
name = "helios_sim"
# Inherit metadata from the workspace
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# Bevy and its ecosystem
bevy = "0.16.0"
avian3d = "0.3.0"
bevy_fly_camera = "0.16.0" # For the debug camera

# The crucial dependency on our pure core library
helios_core = { path = "../helios_core", features = ["bevy"] }
nalgebra = { workspace = true }
serde = { workspace = true }
downcast-rs = "2.0.1"
figment = "0.10.9"
toml = "0.8"                                                   # For parsing scenario files
rand = "0.8"
rand_chacha = "0.3.1"                                          # match bevy
rand_distr = "0.4.3"                                           # match bevy

[dev-dependencies]
approx = "0.5.1"
# approx = {workspace.dev-dependencies = true}
